/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all pages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllPages"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{pageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Page"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Bad request */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AllPages: {
            pageId: string;
            locale: string;
            url: string;
            seo: {
                title: string;
                description: string;
                keywords?: string[];
                schemas: ({
                    /** @enum {string} */
                    type: "article";
                    title: string;
                    description: string;
                    date: string;
                    readingTime: number;
                    keywords: string[];
                } | {
                    /** @enum {string} */
                    type: "person";
                    name: string;
                    jobTitle?: string;
                    description?: string;
                    url?: string;
                    sameAs?: string[];
                } | {
                    /** @enum {string} */
                    type: "product";
                    name: string;
                    description?: string;
                    brand?: string;
                    price?: number;
                    priceCurrency?: string;
                    /** @enum {string} */
                    availability?: "InStock" | "OutOfStock" | "PreOrder";
                })[];
            };
        }[];
        Page: {
            pageId: string;
            locale: string;
            url: string;
            slices: ({
                /** @enum {string} */
                type: "description";
                content: string;
            } | {
                /** @enum {string} */
                type: "text";
                content: string;
            } | {
                /** @enum {string} */
                type: "heading";
                content: string;
                level?: 2 | 3;
            } | {
                /** @enum {string} */
                type: "list";
                content: {
                    ordered?: boolean;
                    items: {
                        text: string;
                    }[];
                };
            } | {
                /** @enum {string} */
                type: "image";
                content: {
                    src: string;
                    alt: string;
                };
            } | {
                /** @enum {string} */
                type: "faq";
                content: {
                    question: string;
                    answer: string;
                }[];
            } | {
                /** @enum {string} */
                type: "space";
            } | {
                /** @enum {string} */
                type: "related";
                content: string[];
            })[];
            seo: {
                title: string;
                description: string;
                keywords?: string[];
                schemas: ({
                    /** @enum {string} */
                    type: "article";
                    title: string;
                    description: string;
                    date: string;
                    readingTime: number;
                    keywords: string[];
                } | {
                    /** @enum {string} */
                    type: "person";
                    name: string;
                    jobTitle?: string;
                    description?: string;
                    url?: string;
                    sameAs?: string[];
                } | {
                    /** @enum {string} */
                    type: "product";
                    name: string;
                    description?: string;
                    brand?: string;
                    price?: number;
                    priceCurrency?: string;
                    /** @enum {string} */
                    availability?: "InStock" | "OutOfStock" | "PreOrder";
                })[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
