/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        timezone: string;
                        language?: string;
                        email?: string;
                        currency?: string;
                        /** @default false */
                        isOnBookWebsite?: boolean;
                        address?: components["schemas"]["Address"];
                    };
                };
            };
            responses: {
                /** @description Create a draft organization, pending an active subscription */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Organization: {
            organizationId: string;
            name: string;
            timezone: string;
            language?: string;
            email?: string;
            currency?: string;
            /** @default false */
            isOnBookWebsite: boolean;
            address?: components["schemas"]["Address"];
            draft?: boolean;
        };
        Address: {
            streetAddress?: string;
            streetNumber?: string;
            addressLocality?: string;
            postalCode?: string;
            addressCountry?: string;
            latitude?: number;
            longitude?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
