/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/booking/range/{organizationId}/{startDate}/{endDate}/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                    startDate: string;
                    endDate: string;
                    serviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all bookings in a given period, serviceId can be 'all' */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"][];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        serviceId: string;
                        slotId?: string;
                        firstName: string;
                        lastName: string;
                        email?: string;
                        phone?: string;
                        additionalInfo?: string;
                        startDate: string;
                        endDate: string;
                        numberOfPerson: number;
                    };
                };
            };
            responses: {
                /** @description Create a booking */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            bookingId: string;
                            serviceId: string;
                            slotId?: string;
                            firstName: string;
                            lastName: string;
                            email?: string;
                            phone?: string;
                            additionalInfo?: string;
                            startDate: string;
                            endDate: string;
                            numberOfPerson: number;
                            /** @enum {string} */
                            status: "booked" | "canceled";
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List all services */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Service"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-provider/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List all service providers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceProvider"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/page/{organizationId}/{pageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                    pageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Page"];
                    };
                };
                /** @description Page not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/page/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List pages of the organization's default website */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllPages"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get organization info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                /** @description Organization not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all orgs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/{organizationId}/{startDate}/{endDate}/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                    startDate: string;
                    endDate: string;
                    serviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all slots, serviceId can be 'all' */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Slot"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Booking: {
            bookingId: string;
            serviceId: string;
            slotId?: string;
            firstName: string;
            lastName: string;
            email?: string;
            phone?: string;
            additionalInfo?: string;
            startDate: string;
            endDate: string;
            numberOfPerson: number;
            /** @enum {string} */
            status: "booked" | "canceled";
            timezone: string;
        };
        Service: {
            serviceId: string;
            name: string;
            description?: string;
        };
        ServiceProvider: {
            serviceProviderId: string;
            firstName: string;
            lastName: string;
            occupationId: string;
            email?: string;
            description?: string;
        };
        Page: {
            organizationId: string;
            websiteId: string;
            pageId: string;
            locale: string;
            url: string;
            slices: ({
                /** @enum {string} */
                type: "description";
                content: string;
            } | {
                /** @enum {string} */
                type: "text";
                content: string;
            } | {
                /** @enum {string} */
                type: "heading";
                content: string;
                level?: 2 | 3;
            } | {
                /** @enum {string} */
                type: "list";
                content: {
                    ordered?: boolean;
                    items: {
                        text: string;
                    }[];
                };
            } | {
                /** @enum {string} */
                type: "image";
                content: {
                    src: string;
                    alt: string;
                };
            } | {
                /** @enum {string} */
                type: "faq";
                content: {
                    question: string;
                    answer: string;
                }[];
            } | {
                /** @enum {string} */
                type: "space";
            } | {
                /** @enum {string} */
                type: "related";
                content: string[];
            })[];
            seo: {
                title: string;
                description: string;
                keywords?: string[];
                schemas: ({
                    /** @enum {string} */
                    type: "article";
                    title: string;
                    description: string;
                    date: string;
                    readingTime: number;
                    keywords: string[];
                } | {
                    /** @enum {string} */
                    type: "person";
                    name: string;
                    jobTitle?: string;
                    description?: string;
                    url?: string;
                    sameAs?: string[];
                } | {
                    /** @enum {string} */
                    type: "product";
                    name: string;
                    description?: string;
                    brand?: string;
                    price?: number;
                    priceCurrency?: string;
                    /** @enum {string} */
                    availability?: "InStock" | "OutOfStock" | "PreOrder";
                })[];
            };
        };
        AllPages: {
            organizationId: string;
            websiteId: string;
            pageId: string;
            locale: string;
            url: string;
            seo: {
                title: string;
                description: string;
                keywords?: string[];
                schemas: ({
                    /** @enum {string} */
                    type: "article";
                    title: string;
                    description: string;
                    date: string;
                    readingTime: number;
                    keywords: string[];
                } | {
                    /** @enum {string} */
                    type: "person";
                    name: string;
                    jobTitle?: string;
                    description?: string;
                    url?: string;
                    sameAs?: string[];
                } | {
                    /** @enum {string} */
                    type: "product";
                    name: string;
                    description?: string;
                    brand?: string;
                    price?: number;
                    priceCurrency?: string;
                    /** @enum {string} */
                    availability?: "InStock" | "OutOfStock" | "PreOrder";
                })[];
            };
        }[];
        Organization: {
            organizationId: string;
            name: string;
            timezone: string;
            isOnBookWebsite: boolean;
            address?: components["schemas"]["Address"];
        };
        Address: {
            streetAddress?: string;
            streetNumber?: string;
            addressLocality?: string;
            postalCode?: string;
            addressCountry?: string;
        };
        Slot: {
            slotId: string;
            serviceId: string;
            maxCapacity: number;
            usedCapacity: number;
            startDate: string;
            endDate: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
