/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List pages of the current organization's website */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllPages"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        locale: string;
                        url: string;
                        slices: ({
                            /** @enum {string} */
                            type: "description";
                            content: string;
                        } | {
                            /** @enum {string} */
                            type: "text";
                            content: string;
                        } | {
                            /** @enum {string} */
                            type: "heading";
                            content: string;
                            level?: 2 | 3;
                        } | {
                            /** @enum {string} */
                            type: "list";
                            content: {
                                ordered?: boolean;
                                items: {
                                    text: string;
                                }[];
                            };
                        } | {
                            /** @enum {string} */
                            type: "image";
                            content: {
                                src: string;
                                alt: string;
                            };
                        } | {
                            /** @enum {string} */
                            type: "faq";
                            content: {
                                question: string;
                                answer: string;
                            }[];
                        } | {
                            /** @enum {string} */
                            type: "space";
                        } | {
                            /** @enum {string} */
                            type: "related";
                            content: string[];
                        })[];
                        seo: {
                            title: string;
                            description: string;
                            keywords?: string[];
                            schemas: ({
                                /** @enum {string} */
                                type: "article";
                                title: string;
                                description: string;
                                date: string;
                                readingTime: number;
                                keywords: string[];
                            } | {
                                /** @enum {string} */
                                type: "person";
                                name: string;
                                jobTitle?: string;
                                description?: string;
                                url?: string;
                                sameAs?: string[];
                            } | {
                                /** @enum {string} */
                                type: "product";
                                name: string;
                                description?: string;
                                brand?: string;
                                price?: number;
                                priceCurrency?: string;
                                /** @enum {string} */
                                availability?: "InStock" | "OutOfStock" | "PreOrder";
                            })[];
                        };
                    };
                };
            };
            responses: {
                /** @description Create a page in the current organization's website */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Page"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/page/{pageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Page"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Page not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delete a page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pageId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        locale?: string;
                        url?: string;
                        slices?: ({
                            /** @enum {string} */
                            type: "description";
                            content: string;
                        } | {
                            /** @enum {string} */
                            type: "text";
                            content: string;
                        } | {
                            /** @enum {string} */
                            type: "heading";
                            content: string;
                            level?: 2 | 3;
                        } | {
                            /** @enum {string} */
                            type: "list";
                            content: {
                                ordered?: boolean;
                                items: {
                                    text: string;
                                }[];
                            };
                        } | {
                            /** @enum {string} */
                            type: "image";
                            content: {
                                src: string;
                                alt: string;
                            };
                        } | {
                            /** @enum {string} */
                            type: "faq";
                            content: {
                                question: string;
                                answer: string;
                            }[];
                        } | {
                            /** @enum {string} */
                            type: "space";
                        } | {
                            /** @enum {string} */
                            type: "related";
                            content: string[];
                        })[];
                        seo?: {
                            title: string;
                            description: string;
                            keywords?: string[];
                            schemas: ({
                                /** @enum {string} */
                                type: "article";
                                title: string;
                                description: string;
                                date: string;
                                readingTime: number;
                                keywords: string[];
                            } | {
                                /** @enum {string} */
                                type: "person";
                                name: string;
                                jobTitle?: string;
                                description?: string;
                                url?: string;
                                sameAs?: string[];
                            } | {
                                /** @enum {string} */
                                type: "product";
                                name: string;
                                description?: string;
                                brand?: string;
                                price?: number;
                                priceCurrency?: string;
                                /** @enum {string} */
                                availability?: "InStock" | "OutOfStock" | "PreOrder";
                            })[];
                        };
                    };
                };
            };
            responses: {
                /** @description Update a page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/website": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List websites of the current organization */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Website"][];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get a page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Locales"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Locales not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Locales"];
                };
            };
            responses: {
                /** @description Update locales of the current organization's website */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List websites of the current organization */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Page: {
            organizationId: string;
            websiteId: string;
            pageId: string;
            locale: string;
            url: string;
            slices: ({
                /** @enum {string} */
                type: "description";
                content: string;
            } | {
                /** @enum {string} */
                type: "text";
                content: string;
            } | {
                /** @enum {string} */
                type: "heading";
                content: string;
                level?: 2 | 3;
            } | {
                /** @enum {string} */
                type: "list";
                content: {
                    ordered?: boolean;
                    items: {
                        text: string;
                    }[];
                };
            } | {
                /** @enum {string} */
                type: "image";
                content: {
                    src: string;
                    alt: string;
                };
            } | {
                /** @enum {string} */
                type: "faq";
                content: {
                    question: string;
                    answer: string;
                }[];
            } | {
                /** @enum {string} */
                type: "space";
            } | {
                /** @enum {string} */
                type: "related";
                content: string[];
            })[];
            seo: {
                title: string;
                description: string;
                keywords?: string[];
                schemas: ({
                    /** @enum {string} */
                    type: "article";
                    title: string;
                    description: string;
                    date: string;
                    readingTime: number;
                    keywords: string[];
                } | {
                    /** @enum {string} */
                    type: "person";
                    name: string;
                    jobTitle?: string;
                    description?: string;
                    url?: string;
                    sameAs?: string[];
                } | {
                    /** @enum {string} */
                    type: "product";
                    name: string;
                    description?: string;
                    brand?: string;
                    price?: number;
                    priceCurrency?: string;
                    /** @enum {string} */
                    availability?: "InStock" | "OutOfStock" | "PreOrder";
                })[];
            };
        };
        AllPages: {
            organizationId: string;
            websiteId: string;
            pageId: string;
            locale: string;
            url: string;
            seo: {
                title: string;
                description: string;
                keywords?: string[];
                schemas: ({
                    /** @enum {string} */
                    type: "article";
                    title: string;
                    description: string;
                    date: string;
                    readingTime: number;
                    keywords: string[];
                } | {
                    /** @enum {string} */
                    type: "person";
                    name: string;
                    jobTitle?: string;
                    description?: string;
                    url?: string;
                    sameAs?: string[];
                } | {
                    /** @enum {string} */
                    type: "product";
                    name: string;
                    description?: string;
                    brand?: string;
                    price?: number;
                    priceCurrency?: string;
                    /** @enum {string} */
                    availability?: "InStock" | "OutOfStock" | "PreOrder";
                })[];
            };
        }[];
        Website: {
            organizationId: string;
            websiteId: string;
            name: string;
            domainId?: string;
        };
        Locales: ("aa" | "ab" | "ae" | "af" | "ak" | "am" | "an" | "ar" | "as" | "av" | "ay" | "az" | "ba" | "be" | "bg" | "bh" | "bi" | "bm" | "bn" | "bo" | "br" | "bs" | "ca" | "ce" | "ch" | "co" | "cr" | "cs" | "cu" | "cv" | "cy" | "da" | "de" | "dv" | "dz" | "ee" | "el" | "en" | "eo" | "es" | "et" | "eu" | "fa" | "ff" | "fi" | "fj" | "fo" | "fr" | "fy" | "ga" | "gd" | "gl" | "gn" | "gu" | "gv" | "ha" | "he" | "hi" | "ho" | "hr" | "ht" | "hu" | "hy" | "hz" | "ia" | "id" | "ie" | "ig" | "ii" | "ik" | "io" | "is" | "it" | "iu" | "ja" | "jv" | "ka" | "kg" | "ki" | "kj" | "kk" | "kl" | "km" | "kn" | "ko" | "kr" | "ks" | "ku" | "kv" | "kw" | "ky" | "la" | "lb" | "lg" | "li" | "ln" | "lo" | "lt" | "lu" | "lv" | "mg" | "mh" | "mi" | "mk" | "ml" | "mn" | "mr" | "ms" | "mt" | "my" | "na" | "nb" | "nd" | "ne" | "ng" | "nl" | "nn" | "no" | "nr" | "nv" | "ny" | "oc" | "oj" | "om" | "or" | "os" | "pa" | "pi" | "pl" | "ps" | "pt" | "qu" | "rm" | "rn" | "ro" | "ru" | "rw" | "sa" | "sc" | "sd" | "se" | "sg" | "si" | "sk" | "sl" | "sm" | "sn" | "so" | "sq" | "sr" | "ss" | "st" | "su" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "ti" | "tk" | "tl" | "tn" | "to" | "tr" | "ts" | "tt" | "tw" | "ty" | "ug" | "uk" | "ur" | "uz" | "ve" | "vi" | "vo" | "wa" | "wo" | "xh" | "yi" | "yo" | "za" | "zh" | "zu")[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
